### ISSUE TITLE
Detex debug call in getdata module

### ISSUE THREAD

**Issue by d-chambers** [d-chambers/Detex#20]
A detex.deb (hardstop debug function) call occurs when an FDSN client fails to fetch data

**Comment by gnpang** [comment]
So, just comment this sentence, right?

**Comment by d-chambers** [comment]
Yes, that should work to get version 1.0.5 running. I will also remove it in the next version which will fix some of the other reported bugs as well.

**Comment by gnpang** [comment]
I got it work and I notice that when using FDSN client to fetch data, st=none this sentence must be remain but using other clients, such as NEIC doesn't. It's because that the FDSN won't return a False to st when it fails to get waveform?

**Comment by d-chambers** [comment]
You are right, good catch. In the earthworm and NEIC tests I did I never had a case where the data didn't exist. 
 Under the except clause in _loadFromNEIC and _loadFromEarthworm st should be assigned to None (or return None would work too), else when it tries to return st it will throw a NameError (because st wont be defined). The function should look like this (I will report and fix this issue too):

``` python
def _loadFromEarthworm(fet, start, end, net, sta, chan, loc):
    client = fet.client
    startstr = start.formatIRISWebService()
    endstr = end.formatIRISWebService()
    st = obspy.Stream()
    for cha in chan:
        try: #try neic client
            st += client.getWaveform(net, sta, loc, cha, start, end)
        except: 
            msg = ('Could not fetch data on %s from %s to %s' % 
            (net + '.' + sta, startstr, endstr))
            detex.log(__name__, msg, level='warning', pri=False)
            st = None
    return st
```
