### ISSUE TITLE
Detex not loading subspace

### ISSUE THREAD

**Issue by SladeBeta** [d-chambers/Detex#30]
I have been trying to get Detex to load the subspace that I created earlier without success. 
The error that I am receiving is regarding "no Subspace stream":

![screenshot 2016-03-02 11 33 46](https://cloud.githubusercontent.com/assets/15039470/13478236/57793752-e08d-11e5-817d-45d53bd4689d.png)

I have attempted to load subspaces created with pickle and mseed formats (thinking there may possibly be some loss of data between formats). Neither one will load properly. 

Below is a snippet of the output created by a subspace that failed to load once written out to the drive.

![screenshot 2016-03-02 15 37 02](https://cloud.githubusercontent.com/assets/15039470/13478316/b8d49a00-e08d-11e5-864e-bda5d545d2c7.png)

This subspace was created with newly downloaded EventWaveform and Continuous data, attempting to look over one month of continuous data.

**Comment by d-chambers** [comment]
This is a bug that results from not having automated tests for this part of the code (I am working on them now). The problem is class was renamed to SubSpace. In util change the function to this:

``` python
def loadSubSpace(filename='subspace.pkl'): 
    """
    Function that uses pandas.read_pickle to load a pickled subspace
    (instance of detex.subspace.SubSpaceStream)
    Parameters
    ----------
    filename : str
        Path to the saved subspace instance
    Returns
    ----------
    An instance of detex.subspace.SubSpaceStream 
    """
    ss = pd.read_pickle(filename)
    if not isinstance(ss, detex.subspace.SubSpace):
        msg = '%s is not a SubSpaceStream instance' % filename
        detex.log(__name__, msg, level='error')
    return ss
```

**Comment by SladeBeta** [comment]
Thanks for letting me know. I'm glad that I'm able to load the SubSpaces now.
