### ISSUE TITLE
Clustering returning empty link matrix

### ISSUE THREAD

**Issue by d-chambers** [d-chambers/Detex#6]
I've been trying to create clusters and haven't been having any luck. I keep getting this error:

---

![screen shot 2015-10-13 at 1 58 47 pm](https://cloud.githubusercontent.com/assets/11671536/10472775/45fd6868-71d9-11e5-9c1d-9095f29cc670.png)

---

I've attached the Template Key and the Station Key files that I'm using. I did try running the tutorial again to be sure it wasn't Detex and the tutorial ran correctly. I tried just running the clustering on one station (IMU) and I still received the same error. I'm going to keep trying to figure out why I'm having this trouble, but any insight into the issue would be great. 

Oh, I can pull data, it's just getting the cluster to form that I'm having issue. 

If it helps to narrow the issue, I also have had trouble creating a subspace. I thought that maybe it was my previous cluster (which created correctly just a few days ago (with more stations in the Station Key and more events in the Template Key) so I tried remaking the cluster and I started receiving the above error. 

[StationKey.txt](https://github.com/d-chambers/Detex/files/12889/StationKey.txt)
[TemplateKey.txt](https://github.com/d-chambers/Detex/files/12888/TemplateKey.txt)

**Comment by d-chambers** [comment]
Short answer:

Rather than using default value of trim = [30, 150],  (which means 30 sec before origin and 150 sec after) use tighter parameters like trim = [1, 35]

Long answer:

What is happening here is that you are mixing event files that have full continuous event data and files that only have a short amount of data available around the origin time. When the default trim value is used in the detex.subspace.createCluster call it results in event data with vastly different lengths, those that have data available for the full 3 minute range and those that only have a small amount of data around the origin available. Detex tries to throw out traces with outlier lengths in the _testStreamLengths call, which results in throwing all of your data away for station IMU. This behavior will be corrected in a future version but for now just shorten the trim window.

**Comment by SladeBeta** [comment]
Okay. That makes sense. Thanks for the help. I'm glad that it was something
simple.
