### ISSUE TITLE
Error messages when running ss.SVD and the final ss.detex steps

### ISSUE THREAD

**Issue by chasebatch** [d-chambers/Detex#7]
I have been able to successfully run detex subspace on my stations for the year 2003, however when I try to add another year (in this case 2004, but it has happened with other years as well) I get the following message when running ss.SVD()
![2003-2004ss svderror](https://cloud.githubusercontent.com/assets/15195673/10764352/521354e0-7c93-11e5-9722-130dae092c7f.png)
To try and continue forward with the program, I set the threshold (ss.SVD(Threshold=0.25)) and run ss.detex(useSingles=True, fillZeros=True), but then get the following error message that looks very similar to the previous one...
![2003-2004ss detexerror](https://cloud.githubusercontent.com/assets/15195673/10764371/70010984-7c93-11e5-90cd-8c61eec54181.png)
I tried attaching my Station and Template Keys to this posting, but it wouldn't let me (said "Attaching documents requires write permission to this repository"). I can email them to you however if needed. All the Continuous Data I have used for these runs has been filtered out using the script you and Kris wrote a few weeks back.

**Comment by d-chambers** [comment]
There is an issue when detex tries to determine the length of continuous data that are not extremely uniform (Kris had this same issue). In the next release this will be fixed but for now simply replace the lines where detex is trying to determine continuous data length with a hard coded value, in your case probably 3720 (1 hour + 2 minutes).

So for example, change line 2459 to:

``` python
self.continuousDataLength = 3720
```

Let me know if that works.

**Comment by chasebatch** [comment]
I made that change, however I still get the same error message.

**Comment by d-chambers** [comment]
Did you load the SubSpaceStream or create a new instance of it? Since this is an attached method to the SubSpaceStream class you will need to create a new instance for the change to work.

**Comment by d-chambers** [comment]
Also, make sure you either reload the subspace module or perform the operation in a new terminal after saving the changes.

**Comment by chasebatch** [comment]
That seems to have done the trick, thanks!
