### ISSUE TITLE
createSubspace routine failing

### ISSUE THREAD

**Issue by kpankow** [d-chambers/Detex#9]
For select the datasets, the createSubspace module fails.  Screen shot of output below.
![screen shot 2015-10-30 at 4 06 48 pm](https://cloud.githubusercontent.com/assets/15475316/10859141/4d6a11a6-7f20-11e5-9b3a-1c6cb7e24c01.png)

Relu has researched this error and it seems that if there are no singletons the program fails.  We think that this is an unwanted feature.  It would be nice to treat all events in an area as a subspace or to look at small datasets that are all correlated.

**Comment by d-chambers** [comment]
Detex now handles singles correctly
